name: build-sphinx-to-gh-pages

on: 
  push:
    branches:
      - master
      - test


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    steps:

      - name: Build Sphinx pages
        run: |
          python3 -m pip install sphinx
          docs/buildsite.sh
